# Generated by Django 5.0.1 on 2024-01-19 07:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_alter_tour_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Contenido'),
        ),
    ]
