# Generated by Django 5.0.1 on 2024-01-19 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la Sección')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Content',
                'verbose_name_plural': 'Content',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DetailSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Título')),
                ('content', models.TextField(verbose_name='Detalle Sección')),
                ('image', models.ImageField(upload_to='lodges', verbose_name='Imagen')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('lodge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lodges.lodge', verbose_name='Lodge')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lodges.section', verbose_name='Sección')),
            ],
            options={
                'verbose_name': 'Detail Content',
                'verbose_name_plural': 'Detail Content',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='lodge',
            name='sections',
            field=models.ManyToManyField(to='lodges.section', verbose_name='Secciones'),
        ),
    ]
